on: [push]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    name: Commit Message Print
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit MessagPr
        id: Testing
#        uses: git-consensus/github-action-verify-address@v1.0
        uses: aagusuab/wallet-commit-check-action@v7.3

