on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Commit Message Print
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit Address Chec
        id: Testing
#        uses: git-consensus/github-action-verify-address@v1.2
        uses: aagusuab/wallet-commit-check-action@v10.2
        with:
          separator: " "

