on: [push]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    name: Commit Message Print
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit Message Pr
        id: Testing
        uses: git-consensus/github-action-verify-address@v1.0

