on: [push]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    name: Commit Message Print
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit Message Print
        id: Testing
        uses: aagusuab/wallet-commit-check-action@v4.3

